name: stalker-portal-proxy

services:
  stalker-portal-proxy:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - cache_data:/data
    restart: unless-stopped

volumes:
  cache_data:
